### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#10]
Сейчас у тебя в папке modules есть файл mixins.pug с тремя миксинами, каждый из которых по сути является самостоятельным блоком. Их можно перенести в components.

_mixins.pug:_
![BEM_001](https://user-images.githubusercontent.com/40715953/76491508-732a2000-6460-11ea-9ccf-62048c8f46de.png)

**Comment by Ilanevazno** [comment]
Полностью согласен. 
Разнёс данные миксины в виде отдельных компонентов, так же дал им более осмыслённые имена.

**Comment by imin314** [comment]
А стили так и остались в общем файле mixins.scss

**Comment by Ilanevazno** [comment]
Готово, раскидал стили по соответствующим компонентам

**Comment by imin314** [comment]
Сейчас лучше, но в папке modules остался файл с переменными variables.scss. Мне кажется, нет смысла хранить его в отдельной папке, когда он скорее относится к файлам стиля.

**Comment by imin314** [comment]
Кстати, scss файл для подключения шрифтов лучше тоже положить в папку styles.

**Comment by Ilanevazno** [comment]
Согласен, переместил выше упомянутые файлы в 'styles'
