### ISSUE TITLE
Хардкод

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#11]
Блоки должны быть переиспользуемыми, т. е. весь контент, который может измениться, нужно передавать через параметры миксина.
Например, в блоке contacts весь текст прописан явно:
![Hardcode_001](https://user-images.githubusercontent.com/40715953/76499116-b9877b00-6470-11ea-85c7-0a0c53cfeb91.png)

**Comment by Ilanevazno** [comment]
Избавил все компоненты от хардкода в этом коммите
https://github.com/Ilanevazno/Resume-the-first-lesson/commit/7124bc9faa7954ae64f64f02f70ee24fb4ddf97a

**Comment by imin314** [comment]
С хардкодом проблема решена:)
Но мне кажется, если использовать деструктуризацию и оператор case в pug, будет более читабельно. Примерно так:
![Screenshot_7](https://user-images.githubusercontent.com/40715953/76678700-84179480-660c-11ea-9143-51f657025904.png)

Посмотри, может, в других файлах деструктуризация тоже облегчит визуальное восприятие кода.

**Comment by imin314** [comment]
По ошибке закрыла эту ишью в прошлый раз и удивляюсь, почему же ты не поправил)

**Comment by Ilanevazno** [comment]
Ты права, с case смотрится бомбезно 😄 
Декструктуризация здесь уже была с закрытием коммента.

**Comment by imin314** [comment]
Эти переменные не используются:
![Screenshot_18](https://user-images.githubusercontent.com/40715953/76825631-11492c00-684d-11ea-95f3-036bbee58023.png)

**Comment by imin314** [comment]
Про деструктуризацию я имела ввиду, что из объекта item записать свойства title, type, text, как ты делал с переменными address, email, tel, website, И вместо того чтобы обращаться к этим свойствам через объект (item.text), использовать переменную (text). Так будет еще круче выглядеть код:) Это во всех файлах надо поправить.

**Comment by Ilanevazno** [comment]
Применил деструктуризацию ко всем компонентам :)
