### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#12]
У тебя сейчас блоки именуются неединообразно. В некоторых есть префиксы block__, блок progress почему-то создан как элемент блока .software.
Также обрати внимание, что папка, содержащая блок, должна иметь такое же имя, как и блок. Например, префиксы mixin в названиях папок не нужны.

**Comment by Ilanevazno** [comment]
в block-header'e был такой префикс, поправил. Блок прогресс вынес в отдельный компонент, имена поправил.

**Comment by imin314** [comment]
Не полностью поправил.
Блок progress, а главный класс .software__progress-item:
![Screenshot_5](https://user-images.githubusercontent.com/40715953/76678008-c342e700-6606-11ea-8b32-df3734dd8085.png)

Если тебе нужно оборачивать progress-item в обертку в блоке .software, делай это там. Например:
```
.software__main
  each item in data
    .software__progress-item        
      +progress-item({ name: item.name, percent: item.percent })
```

**Comment by Ilanevazno** [comment]
Правил именования в данном блоке, прошёл по всем остальным с целью проверки, аналогичных не нашёл)

**Comment by imin314** [comment]
Ага, всё ок теперь. Только не обратила внимания сначала, что у тебя здесь let используется для переменных text и boldText, которые не будут изменяться. Замени на const и закроем ишью:)

**Comment by Ilanevazno** [comment]
Окей, готово, так же по всем остальным файлам тоже пробежался и расставил const вместо let.

**Comment by imin314** [comment]
здесь не поправил:
![Screenshot_15](https://user-images.githubusercontent.com/40715953/76825385-60429180-684c-11ea-87d4-031f32642b46.png)

**Comment by imin314** [comment]
Эти переменные вообще не используются
![Screenshot_16](https://user-images.githubusercontent.com/40715953/76825421-81a37d80-684c-11ea-90e9-afc715fab785.png)

**Comment by imin314** [comment]
![Screenshot_17](https://user-images.githubusercontent.com/40715953/76825554-e19a2400-684c-11ea-98a4-bcbd3c0afc5a.png)

**Comment by Ilanevazno** [comment]
Я сначала не понял как обработать эту ситуацию, ведь с переменной count мы далее работаем, сейчас я разделил на let и const

**Comment by Ilanevazno** [comment]
Мне здесь нужен let, потому что переменные в дальнейшем изменяются.

**Comment by imin314** [comment]
А здесь:
![Screenshot_21](https://user-images.githubusercontent.com/40715953/77029854-82b0e800-69cf-11ea-9eca-786a90ad931a.png)
![Screenshot_22](https://user-images.githubusercontent.com/40715953/77029893-9c522f80-69cf-11ea-8519-e9dd636625e8.png)

Еще обрати внимание, когда имя свойства и значения переменной совпадают (filled: filled), достаточно просто указать filled. В стайлгайде airbnb про это написано.

**Comment by imin314** [comment]
А вот здесь этап деструктуризации лишний - можно же сразу передать объект item в миксин.
![Screenshot_23](https://user-images.githubusercontent.com/40715953/77030061-12ef2d00-69d0-11ea-8159-1e0c97fdb49f.png)

**Comment by Ilanevazno** [comment]
Готово!)
