### ISSUE TITLE
Модификаторы

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#13]
1) Имя модификатора отделяется от имени блока или элемента одним подчеркиванием.
![Снимок экрана в 2020-03-12 16-36-04](https://user-images.githubusercontent.com/40715953/76507557-987a5680-647f-11ea-9bcf-2eba89566bfe.png)

2) Модификатор навешивается на элемент. На скриншоте выше у тебя отсутствует класс элемента, поэтому в scss стили модификатора и элемента объединены в одном классе .intro__circle--blue.

3) Имена модификаторов бывают булевыми и типа "ключ-значение". Например, circle--blue - это модификатор "ключ-значение", но в названии отсутствует ключ. Почитай про именование здесь: [Документация по БЭМ](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80).

**Comment by Ilanevazno** [comment]
Модификатор поправил, с данной документацией ознакомлен, но за ссылку спасибо!)

**Comment by imin314** [comment]
Ты понял про схему именования? Когда модификатор не булевый, нужно перед ним писать ключ. Например, button_size_small, button_size_large. У тебя в названии нет ключа:
![Screenshot_3](https://user-images.githubusercontent.com/40715953/76677962-60515000-6606-11ea-93eb-d7da9d00e75c.png)

**Comment by Ilanevazno** [comment]
Я прошу прощения, сначала не понял о чём речь, мой косяк 😄 .
Документацию перечитал ещё раз, ишью понял, то есть в том случае мне нужно было добавить ключ "color" и значение уже "blue", вместо пустого значения "blue".
Я решил что здесь вообще нет необходимости в этом круге, потому что это аватарка, поэтому немного изменил принцип, теперь там не нужен модификатор.

**Comment by imin314** [comment]
Так еще лучше :)
Только в стандарте airbnb рекомендуется вместо оператора + для объединения строк использовать шаблонные строки. Ты их в других блоках вроде применял, а тут забыл.
![Screenshot_2](https://user-images.githubusercontent.com/40715953/76722817-c4dfec80-6777-11ea-8bcb-610308b39ec6.png)

**Comment by Ilanevazno** [comment]
Готово, провёл интерполяцию во всех файлах)

**Comment by imin314** [comment]
Вот здесь тоже можно поправить:
![Screenshot_14](https://user-images.githubusercontent.com/40715953/76825110-90d5fb80-684b-11ea-8d1b-0438eda6b4b8.png)

**Comment by imin314** [comment]
Хотя в profile можно оставить так.
А еще просто так не нужно шаблонные строки использовать:
![Screenshot_20](https://user-images.githubusercontent.com/40715953/76826179-5b7edd00-684e-11ea-9682-4e02cde81b0d.png)

**Comment by Ilanevazno** [comment]
https://github.com/Ilanevazno/Resume-the-first-lesson/issues/12 вот здесь это захватил

**Comment by imin314** [comment]
С этим блоком еще осталась проблема. Миксин называется circles-progress, а главный класс circles. Название миксина более содержательное, лучше его выбрать для блока.
![Screenshot_20](https://user-images.githubusercontent.com/40715953/77029758-2ea60380-69cf-11ea-8b27-272123a948d9.png)

Кстати, ты обычно пишешь класс не через атрибут, а через точку. Мне кажется, когда класс не вычисляемый, через точку более компактно выглядит.

**Comment by Ilanevazno** [comment]
Исправлено
