### ISSUE TITLE
Стайлгайд для js

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#14]
В файлах pug также требуется следовать рекомендациям из стайлгайдов FSD и airbnb.
Например:
* использовать let, const вместо var,
* отделять содержимое от фигурных скобок пробелами,
![Снимок экрана в 2020-03-12 16-51-02](https://user-images.githubusercontent.com/40715953/76508883-ad57e980-6481-11ea-9972-f22c3ebeaf25.png)

**Comment by Ilanevazno** [comment]
Когда переделывал архитектуру в коммите https://github.com/Ilanevazno/Resume-the-first-lesson/commit/7124bc9faa7954ae64f64f02f70ee24fb4ddf97a данные var'ы включительно изменил (как и в других файлах)

**Comment by imin314** [comment]
Нужно еще проверить, чтобы ; стояли, где надо:
![Screenshot_1](https://user-images.githubusercontent.com/40715953/76677670-bc66a500-6603-11ea-9e68-a356f2f502d1.png)

Ну и для читабельности можно такие короткие конструкции записывать в одну строку. А если будешь в несколько строк, то надо после последнего свойства ставить запятую тоже.

**Comment by imin314** [comment]
Еще ты вроде где-то поправил отступы в фигурных скобках, а где-то не стал.
![Screenshot_2](https://user-images.githubusercontent.com/40715953/76677957-53346100-6606-11ea-8c49-bb4f6ba3a73e.png)

**Comment by Ilanevazno** [comment]
Косяк.. 😢 
Прошёл по всему документу, поправил пробелы у скобок, расставил запятые, точки с запятыми.
