### ISSUE TITLE
index.pug

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#15]
1) Мне кажется, будет лучше, если include поставить в самом начале, чтобы они визуально не разбивали верстку.
2) Не хватает отступов: как будто head, meta, body находятся на том же уровне, что и html.
3) Meta-тэги должны быть вложены в head.
4) Не хватает ключевых слов.
5) charset и viewport обычно задаются в отдельных мета-тэгах.
![Screenshot_1](https://user-images.githubusercontent.com/40715953/76677744-8118a600-6604-11ea-839b-a6d1907b5947.png)

**Comment by imin314** [comment]
А зачем нужны здесь block title и block content?

**Comment by Ilanevazno** [comment]
Исправил все пункты чек листа, сделал отдельный template для главного html файла

**Comment by imin314** [comment]
Теперь ок, но тогда стили main.scss будет логичнее перенести в папку templates.

**Comment by Ilanevazno** [comment]
Перенесено
