### ISSUE TITLE
Несколько миксинов в файле блока

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#16]
Каждый файл блока должен определять только один миксин. В данном случае у тебя миксин experience-settings напрашивается в самостоятельный блок. Кстати, в блоке education есть подобный миксин. Вместо того чтобы создавать два блока experience-settings и education-settings, сделай один блок с подходящим названием. Ведь для этого и нужен БЭМ - чтобы повторно переиспользовать идентичные блоки.
![Screenshot_6](https://user-images.githubusercontent.com/40715953/76678310-567d1c00-6609-11ea-97e3-7768ca51d26a.png)

**Comment by Ilanevazno** [comment]
Проработал общий миксин для обоих данных блоков

**Comment by imin314** [comment]
Гуд!
Только давай теперь по самому миксину пройдемся:
1) Если переменные не планируется изменять, то нужно их объявлять с помощью const. Это во-первых. А во-вторых, данные для миксина practice ты берешь из массива объектов. В самом массиве нет свойств title, date, job... Я бы разделила данные и настройки в разные параметры миксина. Если количество настроек будет расти, то тебе придется каждую явно добавлять в data. Лучше из источника данных только получать информацию и ничего в него не писать, оставляя его неизменяемым.
![Screenshot_9](https://user-images.githubusercontent.com/40715953/76720346-26e82400-676f-11ea-8cbd-49a79b5494c9.png)
2) Кавычки. В JS (даже тот, что в pug) и CSS используй одинарные кавычки. В html - двойные.
![Screenshot_10](https://user-images.githubusercontent.com/40715953/76720895-bcd07e80-6770-11ea-8322-cfb743269c53.png)
3) Само название itemClassName не совсем правильное, так как это имя класса для целого блока, а не для элемента списка (ниже у тебя элементы списка именуются как item).
4) Блок if в js лучше заключать в фигурные скобки.
5) Когда используешь шаблонные строки, можно обойтись без оператора +.
![Screenshot_1](https://user-images.githubusercontent.com/40715953/76721021-281a5080-6771-11ea-99d6-92ccaadebe62.png)

**Comment by Ilanevazno** [comment]
По всему листу с правками пошёлся.
По поводу первого пункта, я конечно не уверен что я правильно понял, но решил убрать данные переменные вовсе (кстати, сначала я и не заметил что они вовсе не использовались 😄  и были абсолютно бесполезными), чтобы использовались только то что приходит из "бэка" грубо говоря.

**Comment by imin314** [comment]
Да немного не так. Сейчас твой миксин принимает два аргумента practice({}, string). При этом, когда ты передаешь второй параметр (на скрине ниже), ты мутируешь первый (объект data). Потом в самом миксине ты получаешь значение модификатора theme не из второго параметра, а из первого мутированного объекта.
![Screenshot_13](https://user-images.githubusercontent.com/40715953/76824748-a860b480-684a-11ea-9469-3bccd5ff3313.png)

Надо сделать так, чтобы вызов миксина был таким: `+practice(data, 'blue');`

**Comment by Ilanevazno** [comment]
Мутирования это плохо, помню из реакта 😄 
Поправил этот момент.
