### ISSUE TITLE
main.scss

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#17]
1) font-family нужно задавать в html. Обрати внимание, какие еще дефолтные параметры должны быть в html. [Пункт 7](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md).
2) Свойство box-sizing в body дублирует аналогичное свойство в селекторе *.
3) Ширину в общих стилях лучше не задавать. Используй для этого соответствующий класс на странице index.
4) В БЭМ не рекомендуется использовать селекторы по тэгам. Исключениями можно назвать общие глобальные стили (например, сброс margin, padding, box-sizing). Свойство text-transform задает стилизацию, поэтому его нужно явно указывать в классах элементов.

**Comment by Ilanevazno** [comment]
Всё понятно, поправил :)
