### ISSUE TITLE
Отступы между селекторами

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#19]
Между стилями для элементов, медиа-запросов, псевдо-классов, псевдо-элементов лучше оставлять пустые строки. Как, например, перед &__text ниже:
![Screenshot_3](https://user-images.githubusercontent.com/40715953/76723121-d07fe300-6778-11ea-9112-804191a7041e.png)

**Comment by Ilanevazno** [comment]
Захватил этот issue во время правки https://github.com/Ilanevazno/Resume-the-first-lesson/issues/20
