### ISSUE TITLE
profile.scss

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#20]
На примере этого файла покажу ошибки в scss. Они точно глобальные, надо проверить везде.

1) Про селекторы по тэгам я уже писала в другом ишью, но на всякий случай повторюсь. Потому что это важно)

2) В классе .profile ты задаешь внешний отступ. Это относится к внешней геометрии, которую по БЭМ ты должен определять вне блока. Представь, что ты захочешь использовать блок profile в нескольких местах с разным положением относительно содержащего элемента. Как тогда будешь задавать отступы? Вариантов, конечно, много, но при таком подходе у тебя либо внешний код будет лезть во внутреннюю реализацию блока, либо придется для каждого варианта отступа писать свой модификатор. Проще всего во внешнем коде поместить блок profile в div-обертку, где ты и будешь задавать margin.

3) Здесь ты как раз пытаешься в блоке profile залезть в стили блока, чтобы добавить margin-top (зачем, кстати?).
![Screenshot_4](https://user-images.githubusercontent.com/40715953/76723703-c5c64d80-677a-11ea-8957-44a723599eca.png)
Если ты хочешь управлять положением блока block-header, то используй прием с элементом оберткой. Например:
```
.profile
  .profile__block-header // этому элементу можно задать положение
    +block__header....
```
А еще сейчас этот margin-top не применяется к img внутри block-header, потому что селектор ищет .profile__header img.

**Comment by Ilanevazno** [comment]
Этот ишью был страшен для меня, если честно. Изначально я не совсем понимал концепцию "внешней геометрии", но теперь всё стало ясно... Это же гениально и круто!) Спасибо.)
А так, всё отсюда поправил

**Comment by imin314** [comment]
Так лучше. Но селекторы по тэгам не все убрал:
![Screenshot_11](https://user-images.githubusercontent.com/40715953/76824253-27ed8400-6849-11ea-8d16-2e45776cc363.png)

**Comment by imin314** [comment]
И внешние отступы еще остались в других блоках:
![Screenshot_12](https://user-images.githubusercontent.com/40715953/76824324-64b97b00-6849-11ea-8cb9-75c990ebae0e.png)

Надо перепроверить.

**Comment by Ilanevazno** [comment]
Прошёлся по всем блокам, убрал внешние отступы.
