### ISSUE TITLE
Используй краткую форму записи свойств css

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#21]
Вот здесь, например, можно использовать свойство _font_:
![Screenshot_5](https://user-images.githubusercontent.com/40715953/76724001-f22e9980-677b-11ea-8999-1f7c93f9cfd4.png)

А тут margin:
![Screenshot_6](https://user-images.githubusercontent.com/40715953/76724049-1a1dfd00-677c-11ea-9fb3-a6009c3c0262.png)

Посмотри статью на [mdn про shorthand properties](https://developer.mozilla.org/ru/docs/Web/CSS/Shorthand_properties). Там в самом низу есть список возможных свойств.

**Comment by Ilanevazno** [comment]
Пробежался по всему проекту, поправил fonts, padding, margin. 
Про краткое использование font'a узнал в 'только что' лет 😸 , изначально испугался, но с 3-4 правки уже запомнил, удобная штучка. Увлекаться не стал, оставил сокращённое свойство фонта там где переопределяется font-family либо имеется около 3 свойств.
