### ISSUE TITLE
Отрицательный margin

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#22]
В стандартах не рекомендуется использовать отрицательные margin:
![Screenshot_7](https://user-images.githubusercontent.com/40715953/76724173-a7615180-677c-11ea-9f77-b4fbab051550.png)

**Comment by Ilanevazno** [comment]
Захватил отрицательный margin вот в этом ишью https://github.com/Ilanevazno/Resume-the-first-lesson/issues/21

**Comment by imin314** [comment]
Здесь пропустил:
![Screenshot_10](https://user-images.githubusercontent.com/40715953/76823888-0c35ae00-6848-11ea-8ecc-5548949cacaa.png)

**Comment by Ilanevazno** [comment]
Здесь я использовал приём центрирования из одной из статей которые увидел же в полезных материалах в FSD https://www.w3.org/Style/Examples/007/center.ru.html

**Comment by Ilanevazno** [comment]
Решил проблему с отрицательным margin'ом
