### ISSUE TITLE
Медиа-запросы

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#23]
По стандартам все медиа запросы элементов должны располагаться рядом с соответствующим элементом. См. [стандарт (пункт 14)](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md).

У тебя сейчас медиа-запросы лежат в общем файле media.scss, что затрудняет переиспользование и модификацию блоков (если, например, нужно будет перенести блок в другой проект, придется искать стили медиа-запросов в этом файле и вручную копировать)

**Comment by Ilanevazno** [comment]
Захватил тему с запросами в ишью https://github.com/Ilanevazno/Resume-the-first-lesson/issues/20 . Убрал страшный стилевой файл на 50+ строк, и теперь весь адаптив занимает пару строк кода 😄
