### ISSUE TITLE
Примеси

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#25]
Здесь ты блоку circles-progress передаешь класс через параметр. По стандартам компании примеси использовать не рекомендуется. Вместо этого ты должен в блоке circles-progress определить все возможные состояния этого компонента и предусмотреть модификаторы.
![Screenshot_24](https://user-images.githubusercontent.com/40715953/77030368-f1db0c00-69d0-11ea-8dfd-7305700b0623.png)

При вызове миксина circles-progress по идее нужно передавать значение модификатора вместо класса. Например: `+circles-progress({ filled, count: max, type: 'skills' })`, потом в блоке ты задаешь класс (примерный код):
```
const typeModifiers = { skills: 'circles-progress__type-skills' };
.circles-progress(class=typeModifiers[type])
```

Но в случае этого блока непонятно, зачем тебе вообще нужно определять стили &__item в классе, который навешиваешь снаружи блока. Нужно их напрямую написать в &__item, а в модификаторе &_filled должен быть только одно свойство, переопределяющее цвет фона.

**Comment by Ilanevazno** [comment]
Эта примесь ещё со старых правок осталась, она бесполезна, просто убрать забыл. Поправил :)
