### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#26]
Надо проверить стили для медиазапросов. Сейчас для мобильных экранов иконки рястягиваются, заголовки не помещаются.
![Screenshot_20](https://user-images.githubusercontent.com/40715953/77158817-a6ab2100-6ad6-11ea-8921-07042d46e48f.png)
![Screenshot_21](https://user-images.githubusercontent.com/40715953/77158818-a7dc4e00-6ad6-11ea-81c8-8965c7483ae9.png)

**Comment by Ilanevazno** [comment]
Да, после рефакторинга ишью с запросам, один из них потерялся.
Поправил данный момент

**Comment by imin314** [comment]
Есть еще несколько моментов, которые надо учесть в медиазапросах:

Когда уменьшаешь разрешение экрана, границы иконки становятся нечеткими. Лучше установить минимальные размеры, сопоставимые размеру текстового заголовка:
![Снимок экрана от 2020-03-21 23-17-19](https://user-images.githubusercontent.com/40715953/77231360-f409ba00-6bcc-11ea-8dee-d826432abeb8.png)

Из-за того что у тебя явно задан line-height, высота строк становится слишком большой. Надо либо указывать line-height коэффициентом (например, 1.6 без единиц измерения), либо тоже в ремах.
![Снимок экрана от 2020-03-21 23-17-49](https://user-images.githubusercontent.com/40715953/77231461-a9d50880-6bcd-11ea-971f-633fc55febae.png)

На маленьком экране лучше компоновать блоки немного плотнее, чтобы не терять драгоценное пространство на пустые отступы. Вот здесь, например, отступ справа от маркера визуально слишком большой и сам маркер сместился по вертикали.
![Снимок экрана от 2020-03-21 23-20-43](https://user-images.githubusercontent.com/40715953/77231496-ed2f7700-6bcd-11ea-9d68-329ee01903b5.png)

Нужно задать максимальную ширину, чтобы кругляши не разъезжались:
![Снимок экрана от 2020-03-21 23-22-31](https://user-images.githubusercontent.com/40715953/77231553-4a2b2d00-6bce-11ea-902e-8526881fa095.png)

**Comment by Ilanevazno** [comment]
Такие моменты конечно остаются на совести дизайнера, т.к макета для мобилок нет, но всё же после это правки стало определённо лучше :)
В общем, поправил 😄
