### ISSUE TITLE
Лишний элемент-обертка с внешним отступом

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#28]
Класс .practice задает только margin. Свойство display: flex никак не влияет на отображение, потому что единственный элемент - это .practice__list. 
![Screenshot_24](https://user-images.githubusercontent.com/40715953/77159684-6482df00-6ad8-11ea-8ae4-489077e2b568.png)

Тебе нужно убрать `<div class="practice">`, а `<ul>` сделать главным в блоке. Внешние отступы задавать в элементе обертке .main-item.

**Comment by Ilanevazno** [comment]
Поправил
