### ISSUE TITLE
Константин Константинопольский

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#29]
Нужно проверять, как будут выглядеть такие элементы с более длинным текстом:
![Screenshot_25](https://user-images.githubusercontent.com/40715953/77160367-c1cb6000-6ad9-11ea-9dbe-e45df84057a5.png)

В данном случае надо хотя бы сделать так, чтобы строки не перекрывали друг друга.

**Comment by Ilanevazno** [comment]
Готово. Теперь данный Константин сможет без проблем использовать свои инициалы :)
