### ISSUE TITLE
Хранение картинок

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#31]
Если картинки используются только в блоке, то их нужно положить в папку блока в подпапку img. Общие картинки хранятся в assets.
![Screenshot_27](https://user-images.githubusercontent.com/40715953/77160959-1ae7c380-6adb-11ea-90e4-aa6615243281.png)

**Comment by Ilanevazno** [comment]
Оу.. даже так.
Поправил ;)
