### ISSUE TITLE
Миксы

### ISSUE THREAD

**Issue by Feinminen** [Ilanevazno/Resume-the-first-lesson#34]
Навешивание на одну сущность несколько элементов - тоже, по факту, является примесью/миксом и по нашим стандартам это не ок. Да и не совсем понятно, зачем для всех элементов-лэйблов отдельный класс, который просто будет навешивать стили шрифта.
![image](https://user-images.githubusercontent.com/44312820/85224777-d976f500-b3f6-11ea-9055-c0702bd3e545.png)

**Comment by Ilanevazno** [comment]
Поправил)

**Comment by Ilanevazno** [comment]
в UI-kit аналогично поправил.
