### ISSUE TITLE
Деструктуризация и параметры по дефолту

### ISSUE THREAD

**Issue by Feinminen** [Ilanevazno/Resume-the-first-lesson#35]
Не совсем понимю зачем сначала дефолтным параметром указывать пустой объект и в уже в теле при деструктуризации указывать дефолтные значения для каждого из полей. Можно же сразу деструктурировать и указать дефолтные значения(как на втором скрине). Я в нескольких местах это видел, чекни по всему проекту.
![image](https://user-images.githubusercontent.com/44312820/85224995-43dc6500-b3f8-11ea-8778-d0972752d0e7.png)
![image](https://user-images.githubusercontent.com/44312820/85225188-8b172580-b3f9-11ea-91ba-29ce245f5c50.png)

**Comment by Feinminen** [comment]
Не буду отдельное ищью открывать, но у тебя два одинаковый стилевых фала в блоке practice осталось, в папке style со старой версии, видимо :)
![image](https://user-images.githubusercontent.com/44312820/85225237-d9c4bf80-b3f9-11ea-820b-abfa7bb92258.png)

**Comment by Ilanevazno** [comment]
Данный вид нужен был для улучшения читаемости. Я по всему проекту поправил, если аргументов по умолчанию будет больше чем 4, тогда лучше использовать предыдущий вид деструктуризации.
