### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#8]
В readme нужно добавить команды для клонирования репозитория и установки зависимостей

**Comment by Ilanevazno** [comment]
Добавлено

**Comment by imin314** [comment]
Нужно указать именно команду для клонирования, чтобы можно было ее скопировать, вставить в консоль и склонировать проект.
А еще не вижу команду для установки.

**Comment by Ilanevazno** [comment]
Понял, добавил команду для установки и клонирования
