### ISSUE TITLE
Импорт стилей

### ISSUE THREAD

**Issue by imin314** [Ilanevazno/Resume-the-first-lesson#9]
Стили и js нужно импортить автоматически, чтобы при изменении и создании блоков не нужно было прописывать их вручную в index.js.
Также файлы со стилями блоков можно импортить напрямую, не создавая js в блоках.

_index.js:_
![Снимок экрана в 2020-03-12 12-27-28](https://user-images.githubusercontent.com/40715953/76490129-df0a8980-645c-11ea-9665-94cbc73eb9b7.png)

**Comment by Ilanevazno** [comment]
Добавил авто-импорты
